### ISSUE TITLE
Application opens but is invisible

### ISSUE THREAD

**Issue by Lefkowitz-s** [intiface/intiface-central#92] opened 2023-10-09 20:12 UTC
Recently, when I tried to open Intiface Central, it opened but did not display a window. The tab was there in the taskbar, but hovering over it displayed an empty preview, and clicking it did not change anything visible. This problem persisted even when I reinstalled Intiface, as well as installing a previous version. Any idea what's going on, or how I can fix it. I did already try restarting my computer.

**Comment by qdot** [comment] 2023-10-09 20:25
Yup, we're aware. This is already filed in

https://github.com/intiface/intiface-central/issues/87

I'm going to try to get it fixed in the next version. For now, you can try deleting the configuration files at `c:\Users\[your user name]\AppData\Roaming\com.nonpolynomial\intiface_central\config\` (or just blow away the whole intiface_central directory)

**Comment by qdot** [comment] 2023-10-09 20:25
Closing as duplicate of #87, watch that bug for fixes.

**Closed by qdot** 2023-10-09 20:25 UTC
